import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS Simple Mailer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.heading}>Next JS Simple Mailer</h1>

      <div className={styles.mailbox}>
        <div>
          <input type="email" className={styles.inputEmail} placeholder="Enter Email" required/>
        </div>

        <div>
          <input type="email" className={styles.inputEmail} value="vaishnavirtc@gmail.com" disabled/>
        </div>

        <div>
          <textarea className={styles.inputText}></textarea>
        </div>
        <button type="button" className={styles.buttonSend}>Send Email</button>
      </div>


    </div>
  )
}
