import { useState } from "react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import axios from "axios";

export default function Home() {

  const [to, setTo] = useState("");
  const [subject, setSubject] = useState("")
  const [text, setText] = useState("");

  async function sendEmail() {
    const response = await axios.post("/api/mail", {
      to: to,
      subject: subject,
      text: text
    })
    console.log(response.data)
    alert('Email send successfully')
    setTo("")
    setSubject("")
    setText("")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS Simple Mailer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.heading}>Next JS Simple Mailer</h1>

      <div className={styles.mailbox}>
        <div>
          <input type="email" className={styles.inputEmail} placeholder="Enter Email"
            value={to}
            onChange={(e) => { setTo(e.target.value) }}
            required />
        </div>

        <div>
          <input type="text" className={styles.inputSubject} placeholder="Enter Subject"
            value={subject}
            onChange={(e) => { setSubject(e.target.value) }}
          />
        </div>

        <div>
          <textarea className={styles.inputText}
          value={text}
            onChange={(e) => { setText(e.target.value) }}
          ></textarea>
        </div>
        <button type="button" onClick={sendEmail} className={styles.buttonSend}>Send Email</button>
      </div>

    </div>
  )
}
